---
title: "5320HW1"
author: "Daniel Silva"
date: "2/17/22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1 

```{r}
set.seed(5320)
n <- 10
x1 <- rnorm(n,8,4)
x2 <- runif(n,0,12)
X <- rbind(x1,x2)
```

# Part a

Find the expectation E[X] and the variance matrix Var[X] of the random vector X

$E[X] = [8,6]'$

$Var[X] = [4,0;0,12]$

```{r}
mu_x = matrix(c(8,6),2,1,byrow=TRUE)
var_x = matrix(c(4,0,0,12),2,2,byrow=TRUE)
```

# Part b 

Find a matrix A and a column vector b such that Y = [Y1,Y2,Y3]' = AX+b

$[1,1,0;1,-1,0;5,0,0]*[x1,x2,x3]' = A*[x1,x2,x3]' + b$

where $A = [1,1,0;1,-1,0;5,0,0]$ and $b = [0,0,10]'$

```{r}
y1 = x1+x2
y2 = x1-x2
y3 = 5*x1+10
Y = rbind(y1,y2,y3)

A = matrix(c(1,1,0,1,-1,0,5,0,0),3,3,byrow=TRUE)
b = matrix(c(0,0,10),3,1,byrow=TRUE)
 
```

# Part c 

Find the expectation E[Y] and Var[Y] of the random variable Y. 

$E[Y] = E[[Y1,Y2,Y3]'] = [E[Y1],E[Y2],E[Y3]]'$ 
$= [ E[X1]+E[X2],E[X1]-E[X2],5*E[X1]-10]'$
$= [ 8+6, 8-6, 5*8 ]'$
$= [14, 2, 30]'$

$Var(Y) = Var([Y1,Y2,Y3]')$

$$Var(Y) = \begin{bmatrix} Var(Y1) & Cov[Y1,Y2] & Cov[Y1,Y3] \\
 Cov[Y2,Y1] & Var(Y2) & Cov[Y2,Y3] \\
Cov[Y3,Y1] & Cov[Y3,Y2] & Var(Y3) \\
\end{bmatrix}$$


$$Var(Y) = \begin{bmatrix} Var(X1+X2) & Cov[X1+X2,X1-X2] & Cov[X1+X2,5*X1+10] \\
Cov[X1-X2,X1+X2] & Var(X1-X2) & Cov[X1-X2,5*X1+10] \\
Cov[5*X1+10,X1+X2] & Cov[5*X1+10,X1-X2] & Var(5*X1+10) \\
\end{bmatrix}$$

$$Var(Y) = \begin{bmatrix} Var(X1)+Var(X2) & Cov[X1,X1]-Cov[X2,X2]+Cov[X2,X1]-Cov[X2,X1] & Cov[X1]

## Problem 2


